spring.application.name=api

#PostgreSQL Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5433/livraria
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring Data JPA & Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
